name: C/C++ build

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install ncurses
      run: sudo apt-get install libncurses5-dev libncursesw5-dev
    - name: compile everything
      run: make main
